# Generated by Django 5.0.3 on 2024-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_lesson_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='term',
            field=models.IntegerField(),
        ),
    ]
