# Generated by Django 5.0.3 on 2024-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_lesson_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
