# Generated by Django 5.0.3 on 2024-03-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/quiz_image'),
        ),
    ]
