# Generated by Django 5.0.3 on 2024-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
