# Generated by Django 5.0.3 on 2024-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='discipline',
            field=models.CharField(choices=[('1', 'پزشکی'), ('2', 'پرستاری')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
