# Generated by Django 5.0.3 on 2024-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discipline',
            field=models.CharField(choices=[('1', 'پزشکی'), ('2', 'پرستاری')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'آقا'), ('2', 'خانم')], max_length=7),
        ),
    ]
