# Generated by Django 5.0.3 on 2024-04-07 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numerical values are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='term',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
