# Generated by Django 5.0.3 on 2024-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ipadress_alter_verificationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
