# Generated by Django 5.0.3 on 2024-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takingtest', '0003_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='primary_number',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='primary_number',
            field=models.UUIDField(null=True),
        ),
    ]
