# Generated by Django 5.0.3 on 2024-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takingtest', '0004_quizhistory_primary_number_quizresult_primary_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
