# Generated by Django 5.0.3 on 2024-03-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takingtest', '0005_quizresult_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizhistory',
            old_name='primary_number',
            new_name='exam_number',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='primary_number',
            new_name='exam_number',
        ),
    ]
